WITH MAX_COUNT AS (
    SELECT P.MEMBER_ID,
        P.MEMBER_NAME,
        COUNT(*) AS REVIEW_COUNT
    FROM MEMBER_PROFILE AS P
        JOIN REST_REVIEW AS R USING (MEMBER_ID)
    GROUP BY P.MEMBER_ID,
        P.MEMBER_NAME
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)
SELECT M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW AS R
    JOIN MAX_COUNT AS M ON R.MEMBER_ID = M.MEMBER_ID
ORDER BY R.REVIEW_DATE;