SELECT CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
FROM (
        SELECT CATEGORY,
            PRICE,
            PRODUCT_NAME,
            RANK() OVER (
                PARTITION BY CATEGORY
                ORDER BY PRICE DESC
            ) AS FOOD_RANK
        FROM FOOD_PRODUCT
    ) T
WHERE FOOD_RANK = 1
    AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;
-- SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
-- FROM FOOD_PRODUCT
-- WHERE (CATEGORY, PRICE) IN (
--     SELECT CATEGORY, MAX(PRICE)
--     FROM FOOD_PRODUCT
--     GROUP BY CATEGORY
-- )
-- AND CATEGORY IN ('과자','국','김치','식용유')
-- ORDER BY PRICE DESC;