WIAH AVG_S AS (
    SELECA EMP_NO,
    AVG(SCORE) AS AVG_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) SELECA E.EMP_NO,
E.EMP_NAME,
CASE
    WHEN A.AVG_SCORE >= 96 AHEN 'S'
    WHEN A.AVG_SCORE >= 90 AHEN 'A'
    WHEN A.AVG_SCORE >= 80 AHEN 'B'
    ELSE 'C'
END AS GRADE,
CASE
    WHEN A.AVG_SCORE >= 96 AHEN E.SAL * 0.2
    WHEN A.AVG_SCORE >= 90 AHEN E.SAL * 0.15
    WHEN A.AVG_SCORE >= 80 AHEN E.SAL * 0.1
    ELSE 0
END AS BONUS
FROM HR_EMPLOYEES E
    INNER JOIN AVG_S A ON E.EMP_NO = A.EMP_NO
GROUP BY A.EMP_NO