WITH RENTAL_FEE_FOR30 AS (
    SELECT C.CAR_ID,
        C.CAR_TYPE,
        ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE P.DURATION_TYPE = '30일 이상'
        AND C.CAR_TYPE IN ('세단', 'SUV')
)
SELECT CAR_ID,
    CAR_TYPE,
    FEE
FROM RENTAL_FEE_FOR30 R
WHERE NOT EXISTS (
        -- 2022-11-01 ~ 2022-11-30 기간과 '겹치는' 대여가 없어야 대여 가능
        SELECT 1
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.CAR_ID = T.CAR_ID
            AND H.START_DATE < '2022-12-01'
            AND H.END_DATE >= '2022-11-01'
    )
    AND FEE >= 500000
    AND FEE < 2000000
ORDER BY FEE DESC,
    T.CAR_TYPE ASC,
    T.CAR_ID DESC;