SELECT A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A USING(AUTHOR_ID)
    JOIN BOOK_SALES BS USING(BOOK_ID)
WHERE BS.SALES_DATE LIKE ('2022-01%')
GROUP BY A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY A.AUTHOR_ID ASC,
    B.CATEGORY DESC