WITH TRUCK AS (
    SELECT CAR_ID,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
DISCOUNT_PLAN AS (
    SELECT CAST(
            SUBSTRING_INDEX(DURATION_TYPE, '일', 1) AS UNSIGNED
        ) AS MIN_DAYS,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
RENT_DAYS AS (
    SELECT HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
BEST_DISCOUNT AS (
    SELECT R.HISTORY_ID,
        R.CAR_ID,
        T.DAILY_FEE,
        R.RENTAL_DAYS,
        P.DISCOUNT_RATE,
        ROW_NUMBER() OVER (
            PARTITION BY R.HISTORY_ID
            ORDER BY P.MIN_DAYS DESC
        ) AS RN
    FROM RENT_DAYS R
        JOIN TRUCK T ON R.CAR_ID = T.CAR_ID
        LEFT JOIN DISCOUNT_PLAN P ON R.RENTAL_DAYS >= P.MIN_DAYS
)
SELECT HISTORY_ID,
    FLOOR(
        DAILY_FEE * RENTAL_DAYS * (1 - COALESCE(DISCOUNT_RATE, 0) / 100)
    ) AS FEE
FROM BEST_DISCOUNT
WHERE RN = 1
ORDER BY FEE DESC,
    HISTORY_ID DESC