WITH MAX_VIEW AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT_WS(
        '/',
        '/home/grep/src',
        MV.BOARD_ID,
        CONCAT(F.FILE_ID, F.FILE_NAME, F.FILE_EXT)
    ) AS FILE_PATH
FROM MAX_VIEW MV
    JOIN USED_GOODS_FILE F USING (BOARD_ID)
ORDER BY F.FILE_ID DESC;