SELECT COUNT(*) AS FISH_COUNT,
    MAX(
        CASE
            WHEN `LENGTH` IS NULL
            OR `LENGTH` <= 10 THEN 10
            ELSE `LENGTH`
        END
    ) AS MAX_LENGTH,
    FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(
        CASE
            WHEN `LENGTH` IS NULL
            OR `LENGTH` <= 10 THEN 10
            ELSE `LENGTH`
        END
    ) >= 33
ORDER BY FISH_TYPE ASC;
-- 이건 왜 안될까
-- WITH FISH_LENGTH AS
-- (SELECT FISH_TYPE, CASE
--  WHEN 'LENGTH' <= 10 OR 'LENGTH' IS NULL THEN '10'
--  ELSE 'LENGTH'
--  END AS FISH_LEN
--  FROM FISH_INFO
-- )
-- SELECT COUNT(*) AS FISH_COUNT, 
-- MAX(FISH_LEN) AS MAX_LENGTH, 
-- FISH_TYPE
-- FROM FISH_LENGTH
-- GROUP BY FISH_TYPE
-- HAVING AVG(FISH_LEN) >= 33
-- ORDER BY FISH_TYPE ASC;