WITH agg AS (
    SELECT ROUTE,
        ROUND(SUM(D_BETWEEN_DIST), 1) AS TOTAL,
        ROUND(AVG(D_BETWEEN_DIST), 2) AS AVERAGE
    FROM SUBWAY_DISTANCE
    GROUP BY ROUTE
)
SELECT ROUTE,
    CONCAT(TOTAL, 'km') AS TOTAL_DISTANCE,
    CONCAT(AVERAGE, 'km') AS AVERAGE_DISTANCE
FROM agg
GROUP BY ROUTE
ORDER BY TOTAL DESC;