WITH MAX_YEAR AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
    JOIN MAX_YEAR M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR ASC,
    YEAR_DEV ASC;
-- WINDOW 함수 사용하면 더 깔끔
-- SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
-- (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE))
-- - SIZE_OF_COLONY) AS YEAR_DEV, ID
-- FROM ECOLI_DATA
-- ORDER BY YEAR ASC, YEAR_DEV ASC;