SELECT F.ITEM_ID,
    F.ITEM_NAME,
    F.RARITY
FROM ITEM_TREE AS T
    JOIN ITEM_INFO AS I -- 부모
    ON T.PARENT_ITEM_ID = I.ITEM_ID
    JOIN ITEM_INFO AS F -- 자식
    ON T.ITEM_ID = F.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY F.ITEM_ID DESC;