SELECT DISTINCT(CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H USING (CAR_ID)
WHERE C.CAR_TYPE = '세단'
    AND MONTH(H.START_DATE) = 10
ORDER BY CAR_ID DESC;