WITH TIMEDIFF AS (
    SELECT TIMESTAMPDIFF(DAY, I.DATETIME, O.DATETIME) AS PERIOD,
        O.ANIMAL_ID,
        O.NAME
    FROM ANIMAL_INS I
        JOIN ANIMAL_OUTS O USING(ANIMAL_ID)
)
SELECT ANIMAL_ID,
    NAME
FROM TIMEDIFF
ORDER BY PERIOD DESC
LIMIT 2;