SELECT CASE
        WHEN GROUP_CONCAT(B.NAME) LIKE ("%Python%")
        AND GROUP_CONCAT(B.CATEGORY) LIKE("%Front%") THEN "A"
        WHEN GROUP_CONCAT(B.NAME) LIKE ("%C#%") THEN "B"
        WHEN GROUP_CONCAT(B.CATEGORY) LIKE ("%Front%") THEN "C"
    END AS GRADE,
    A.ID,
    A.EMAIL
FROM DEVELOPERS AS A
    JOIN SKILLCODES AS B ON (A.SKILL_CODE & B.CODE = B.CODE)
GROUP BY ID,
    EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE ASC,
    ID ASC;