WITH J_SUM AS (
    SELECT FLAVOR,
        SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
)
SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN J_SUM J USING (FLAVOR)
ORDER BY (F.TOTAL_ORDER + J.JULY_TOTAL) DESC
LIMIT 3;
-- 이건 왜 안될까
-- WITH SALES AS (
--   SELECT J.FLAVOR,
--          SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_SALES
--   FROM FIRST_HALF F
--   JOIN JULY J USING (SHIPMENT_ID)
--   GROUP BY J.FLAVOR
-- )
-- SELECT FLAVOR
-- FROM SALES
-- ORDER BY TOTAL_SALES DESC
-- LIMIT 3;